### ISSUE TITLE
用户搜索接口

### ISSUE THREAD

**Issue by Sokwva** [zhuweitung/acfun-api-collect#1]
https://www.acfun.cn/rest/pc-direct/search/user?keyword=%E9%BE%99%E9%A6%8D%E9%A6%8D

不需要认证信息

**Comment by zhuweitung** [comment]
已添加，[commit](https://github.com/zhuweitung/acfun-api-collect/commit/3afaec3fb9169c1ffd26359c44d58900a1228858)
